apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  sessionAffinity: "ClientIP"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: delivery
